Refactor shared library script into function for DLX

diff --git a/DLXJenkins/Jenkinsfile b/DLXJenkins/Jenkinsfile
--- a/DLXJenkins/Jenkinsfile
+++ b/DLXJenkins/Jenkinsfile
@@ -5,6 +5,37 @@ def unityUtil
 def sharedLib
 def resultStatus
 
+
+def loadSharedLibrary() {
+    script {
+        try {
+            def LIBRARY_PATH = 'sharedLibraries'
+            echo "Loading local shared library from ${WORKSPACE}/${LIBRARY_PATH}"
+
+            // Create temporary Git repository
+            sh """
+                cd ${WORKSPACE}/${LIBRARY_PATH} && \
+                (rm -rf .git || true) && \
+                git init && \
+                git add --all && \
+                git commit -m 'init'
+            """
+
+            // Get the path of the temporary Git repository
+            def repoPath = sh(returnStdout: true, script: 'pwd').trim() + "/${LIBRARY_PATH}"
+
+            // Shared Library Registration
+            sharedLib = library identifier: 'local-lib@master',
+                    retriever: modernSCM([$class: 'GitSCMSource', remote: "${repoPath}"]),
+                    changelog: false
+            echo 'Successfully loaded shared library'
+        } catch (Exception e) {
+            echo "Failed to load shared library: ${e.message}"
+            error('Shared Library Loading Failed')
+        }
+    }
+}
+
 pipeline {
     agent any
 
@@ -61,33 +92,7 @@ pipeline {
     stages {
         stage('Load Shared Library') {
             steps {
-                script {
-                    try {
-                        def LIBRARY_PATH = 'sharedLibraries'
-                        echo "Loading local shared library from ${WORKSPACE}/${LIBRARY_PATH}"
-
-                        // Create temporary Git repository
-                        sh """
-                            cd ${WORKSPACE}/${LIBRARY_PATH} && \
-                            (rm -rf .git || true) && \
-                            git init && \
-                            git add --all && \
-                            git commit -m 'init'
-                        """
-
-                        // Get the path of the temporary Git repository
-                        def repoPath = sh(returnStdout: true, script: 'pwd').trim() + "/${LIBRARY_PATH}"
-
-                        // Shared Library Registration
-                        sharedLib = library identifier: 'local-lib@master',
-                                retriever: modernSCM([$class: 'GitSCMSource', remote: "${repoPath}"]),
-                                changelog: false
-                        echo 'Successfully loaded shared library'
-                    } catch (Exception e) {
-                        echo "Failed to load shared library: ${e.message}"
-                        error('Shared Library Loading Failed')
-                    }
-                }
+                loadSharedLibrary()
             }
         }
         // Prepare WORKSPACE: Environment Setup, env.WORKSPACE Preparation(Branch Management),
