Reimplement extracted function for prepare shared library with new fix
- Added the @Field attribute which makes it so that the sharedLib variable is able to be used outside the pipeline { } code block. The issue previously was that the extracted function would create a new local variable sharedLib and not use the global defined because thats how Jenkins works.

diff --git a/DLXJenkins/Jenkinsfile b/DLXJenkins/Jenkinsfile
--- a/DLXJenkins/Jenkinsfile
+++ b/DLXJenkins/Jenkinsfile
@@ -2,8 +2,37 @@ def pass = 'Pass'
 def fail = 'Fail'
 def generalUtil
 def unityUtil
+@Field
 def sharedLib
 def resultStatus
+
+def loadSharedLibrary() {
+    try {
+        def LIBRARY_PATH = 'sharedLibraries'
+        echo "Loading local shared library from ${WORKSPACE}/${LIBRARY_PATH}"
+
+        // Create temporary Git repository
+        sh """
+            cd ${WORKSPACE}/${LIBRARY_PATH} && \
+            (rm -rf .git || true) && \
+            git init && \
+            git add --all && \
+            git commit -m 'init'
+        """
+
+        // Get the path of the temporary Git repository
+        def repoPath = sh(returnStdout: true, script: 'pwd').trim() + "/${LIBRARY_PATH}"
+
+        // Shared Library Registration
+        sharedLib = library identifier: 'local-lib@master',
+                retriever: modernSCM([$class: 'GitSCMSource', remote: "${repoPath}"]),
+                changelog: false
+        echo 'Successfully loaded shared library'
+    } catch (Exception e) {
+        echo "Failed to load shared library: ${e.message}"
+        error('Shared Library Loading Failed')
+    }
+}
 
 pipeline {
     agent any
@@ -62,31 +91,7 @@ pipeline {
         stage('Load Shared Library') {
             steps {
                 script {
-                    try {
-                        def LIBRARY_PATH = 'sharedLibraries'
-                        echo "Loading local shared library from ${WORKSPACE}/${LIBRARY_PATH}"
 
-                        // Create temporary Git repository
-                        sh """
-                            cd ${WORKSPACE}/${LIBRARY_PATH} && \
-                            (rm -rf .git || true) && \
-                            git init && \
-                            git add --all && \
-                            git commit -m 'init'
-                        """
-
-                        // Get the path of the temporary Git repository
-                        def repoPath = sh(returnStdout: true, script: 'pwd').trim() + "/${LIBRARY_PATH}"
-
-                        // Shared Library Registration
-                        sharedLib = library identifier: 'local-lib@master',
-                                retriever: modernSCM([$class: 'GitSCMSource', remote: "${repoPath}"]),
-                                changelog: false
-                        echo 'Successfully loaded shared library'
-                    } catch (Exception e) {
-                        echo "Failed to load shared library: ${e.message}"
-                        error('Shared Library Loading Failed')
-                    }
                 }
             }
         }
