Merged in CORE-1543-Integrate-SonarQube-into-PipelineForJenkins (pull request #34)
CORE-1543 Integrate SonarQube into PipelineForJenkins

* Added Load Shared Library stage for PipelineForJenkins

* Temporarily removed Load Shared Library stage

* Retry

* Difference way to implement shared library for jenkins pipeline

* Try without L

* Test UnityHelper Importing package without Load Shared Library

* Try to run work prepare workspace stage with try catch surrounded

* Test Unity Pipeline without Load Shared Library stage

* Added sharedLibraries directory to build.gradle

* Fixed loading shared library

* Fixed Linting

* Fixed Linting again

* Apply shared library for DLX Deployment pipeline

* Fixed linting and Applied shared library for JS pipeline

* Fixed missing double quotes in echo statements

* Fixed CI_PIPELINE variable operation

* Added package importing for jsHelper.groovy

* Added test case for ResultStatus package

* Replace sh 'pwd' with pwd()

* Fixed linting errors

* Fixed linting errors

* Deleted unused function

* Fixed Linting errors

* Groovy Lint disable test

* No parse argument for lint


Approved-by: Jonathan Bezeau

diff --git a/DLXJenkins/Jenkinsfile b/DLXJenkins/Jenkinsfile
--- a/DLXJenkins/Jenkinsfile
+++ b/DLXJenkins/Jenkinsfile
@@ -2,6 +2,8 @@ def pass = 'Pass'
 def fail = 'Fail'
 def generalUtil
 def unityUtil
+def sharedLib
+def resultStatus
 
 pipeline {
     agent any
@@ -57,6 +59,37 @@ pipeline {
     }
 
     stages {
+        stage('Load Shared Library') {
+            steps {
+                script {
+                    try {
+                        def LIBRARY_PATH = 'sharedLibraries'
+                        echo "Loading local shared library from ${WORKSPACE}/${LIBRARY_PATH}"
+
+                        // Create temporary Git repository
+                        sh """
+                            cd ${WORKSPACE}/${LIBRARY_PATH} && \
+                            (rm -rf .git || true) && \
+                            git init && \
+                            git add --all && \
+                            git commit -m 'init'
+                        """
+
+                        // Get the path of the temporary Git repository
+                        def repoPath = sh(returnStdout: true, script: 'pwd').trim() + "/${LIBRARY_PATH}"
+
+                        // Shared Library Registration
+                        sharedLib = library identifier: 'local-lib@master',
+                                retriever: modernSCM([$class: 'GitSCMSource', remote: "${repoPath}"]),
+                                changelog: false
+                        echo 'Successfully loaded shared library'
+                    } catch (Exception e) {
+                        echo "Failed to load shared library: ${e.message}"
+                        error('Shared Library Loading Failed')
+                    }
+                }
+            }
+        }
         // Prepare WORKSPACE: Environment Setup, env.WORKSPACE Preparation(Branch Management),
         // Unity Setup, Initial running the project on Unity Editor
         stage('Prepare WORKSPACE') {
@@ -67,25 +100,28 @@ pipeline {
                         // print jenkins env configurations
                         sh 'env'
                         try {
+                            // Load the necessary packages
+                            resultStatus = sharedLib.resource.ResultStatus
+
                             generalUtil = load("${env.WORKSPACE}/groovy/generalHelper.groovy")
                             unityUtil = load("${env.WORKSPACE}/groovy/unityHelper.groovy")
+
+                            if (generalUtil.isBranchUpToDateWithRemote(PR_BRANCH) && !TEST_RUN.equals('Y')) {
+                                echo 'Local branch commit is up to date with remote branch, no changes. Aborting pipeline.'
+                                currentBuild.result = resultStatus.BUILD_STATUS.ABORTED
+                                error('Branch is up to date, no changes.')
+                            }
+
+                            COMMIT_HASH = generalUtil.getFullCommitHash(env.WORKSPACE, PR_COMMIT)
+
+                            generalUtil.initializeEnvironment(env.WORKSPACE, COMMIT_HASH, PR_BRANCH)
+
+                            generalUtil.cloneOrUpdateRepo(PROJECT_TYPE, env.WORKSPACE, PROJECT_DIR, REPO_SSH, PR_BRANCH)
+
+                            generalUtil.mergeBranchIfNeeded()
                         } catch (Exception e) {
-                            error "Failed to load Groovy scripts: ${e.message}"
+                            error "Failed for Prepare WORKSPACE: ${e.message}"
                         }
-
-                        if (generalUtil.isBranchUpToDateWithRemote(PR_BRANCH) && !TEST_RUN.equals('Y')) {
-                            echo 'Local branch commit is up to date with remote branch, no changes. Aborting pipeline.'
-                            currentBuild.result = 'ABORTED'
-                            error('Branch is up to date, no changes.')
-                        }
-
-                        COMMIT_HASH = generalUtil.getFullCommitHash(env.WORKSPACE, PR_COMMIT)
-
-                        generalUtil.initializeEnvironment(env.WORKSPACE, COMMIT_HASH, PR_BRANCH)
-
-                        generalUtil.cloneOrUpdateRepo(PROJECT_TYPE, env.WORKSPACE, PROJECT_DIR, REPO_SSH, PR_BRANCH)
-
-                        generalUtil.mergeBranchIfNeeded()
                     }
                 }
 
@@ -140,10 +176,10 @@ pipeline {
                                 """
                             }
 
-                        catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
+                        catchError(buildResult: resultStatus.BUILD_STATUS.SUCCESS, stageResult: resultStatus.STAGE_STATUS.FAILURE) {
                             error("Linting failed with exit code: ${exitCode}") //we exit no matter what on error code != 0
                         }
-                        }
+                    }
                     else {
                         echo """ Parameters for Python Pass: \\
                             \'${env.WORKSPACE}/python/linting_error_report.py\' \\
diff --git a/DLXJenkins/JenkinsfileDeployment b/DLXJenkins/JenkinsfileDeployment
--- a/DLXJenkins/JenkinsfileDeployment
+++ b/DLXJenkins/JenkinsfileDeployment
@@ -1,6 +1,8 @@
 def generalUtil
 def unityUtil
 def mainBranches = ['main', 'master']
+def sharedLib // Use this variable to store the shared library, work as import statement
+def resultStatus // Use this variable to store the package of result status, work as import statement
 
 pipeline {
     agent any
@@ -36,7 +38,7 @@ pipeline {
     }
 
     environment {
-        CI_PIPELINE = 'false'
+        CI_PIPELINE = false
         PROJECT_TYPE = 'Unity_Project'
         PROJECT_DIR = "${env.WORKSPACE}/${PROJECT_TYPE}"
         REPORT_DIR = "${env.WORKSPACE}/DeploymentJob/${PR_BRANCH}"
@@ -47,20 +49,54 @@ pipeline {
     }
 
     stages {
+        stage('Load Shared Library') {
+            steps {
+                script {
+                    try {
+                        def LIBRARY_PATH = 'sharedLibraries'
+                        echo "Loading local shared library from ${WORKSPACE}/${LIBRARY_PATH}"
+
+                        // Create temporary Git repository
+                        sh """
+                            cd ${WORKSPACE}/${LIBRARY_PATH} && \
+                            (rm -rf .git || true) && \
+                            git init && \
+                            git add --all && \
+                            git commit -m 'init'
+                        """
+
+                        // Get the path of the temporary Git repository
+                        def repoPath = sh(returnStdout: true, script: 'pwd').trim() + "/${LIBRARY_PATH}"
+
+                        // Shared Library Registration
+                        sharedLib = library identifier: 'local-lib@master',
+                                retriever: modernSCM([$class: 'GitSCMSource', remote: "${repoPath}"]),
+                                changelog: false
+                        echo 'Successfully loaded shared library'
+                    } catch (Exception e) {
+                        echo "Failed to load shared library: ${e.message}"
+                        error('Shared Library Loading Failed')
+                    }
+                }
+            }
+        }
         // Deletes the cloned branch from the build machine after it has been merged into main.
         // This prevents the build machine's storage from capping out.
         stage('Delete Merged Branch') {
             steps {
                 script {
-                    // Aborts the pipeline if it's not merging into the main.
-                    if (!mainBranches.contains(DESTINATION_BRANCH)) {
-                        env.FAILURE_REASON = 'Not merging to the main branch. Exiting the pipeline...'
-                        currentBuild.result = 'ABORTED'
-                        error(env.FAILURE_REASON)
-                    }
+                    // Load the necessary packages
+                    resultStatus = sharedLib.resource.ResultStatus
 
                     generalUtil = load("${env.WORKSPACE}/groovy/generalHelper.groovy")
                     unityUtil = load("${env.WORKSPACE}/groovy/unityHelper.groovy")
+
+                    // Aborts the pipeline if it's not merging into the main.
+                    if (!mainBranches.contains(DESTINATION_BRANCH)) {
+                        env.FAILURE_REASON = 'Not merging to the main branch. Exiting the pipeline...'
+                        currentBuild.result = buildResults.ABORTED
+                        error(env.FAILURE_REASON)
+                    }
 
                     // Getting the full commit hash from git in order to send the build status to Bitbucket.
                     COMMIT_HASH = generalUtil.getFullCommitHash(env.WORKSPACE, PR_COMMIT)
@@ -138,7 +174,7 @@ pipeline {
                     //handle exit code here no reports to be sent, since this for deployment and not PRs
                     if (exitCode != 0) {
                         //in this case we set build result to failure since we don't want to deploy bad code
-                        catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
+                        catchError(buildResult: resultStatus.BUILD_STATUS.SUCCESS, stageResult: resultStatus.STAGE_STATUS.FAILURE) {
                             error("Linting failed with exit code: ${exitCode}") //we exit no matter what on error code != 0
                         }
                     }
diff --git a/JsJenkins/Jenkinsfile b/JsJenkins/Jenkinsfile
--- a/JsJenkins/Jenkinsfile
+++ b/JsJenkins/Jenkinsfile
@@ -1,5 +1,7 @@
 def generalUtil
 def jsUtil
+def sharedLib // Use this variable to store the shared library, work as import statement
+def resultStatus // Use this variable to store the package of result status, work as import statement
 
 pipeline {
     agent any
@@ -58,6 +60,37 @@ pipeline {
     }
 
     stages {
+        stage('Load Shared Library') {
+            steps {
+                script {
+                    try {
+                        def LIBRARY_PATH = 'sharedLibraries'
+                        echo "Loading local shared library from ${WORKSPACE}/${LIBRARY_PATH}"
+
+                        // Create temporary Git repository
+                        sh """
+                            cd ${WORKSPACE}/${LIBRARY_PATH} && \
+                            (rm -rf .git || true) && \
+                            git init && \
+                            git add --all && \
+                            git commit -m 'init'
+                        """
+
+                        // Get the path of the temporary Git repository
+                        def repoPath = sh(returnStdout: true, script: 'pwd').trim() + "/${LIBRARY_PATH}"
+
+                        // Shared Library Registration
+                        sharedLib = library identifier: 'local-lib@master',
+                                retriever: modernSCM([$class: 'GitSCMSource', remote: "${repoPath}"]),
+                                changelog: false
+                        echo 'Successfully loaded shared library'
+                    } catch (Exception e) {
+                        echo "Failed to load shared library: ${e.message}"
+                        error('Shared Library Loading Failed')
+                    }
+                }
+            }
+        }
         // Prepare WORKSPACE: Environment Setup, WORKSPACE Preparation(Branch Management),
         //  Unity Setup, Initial running the project on Unity Editor
         stage('Prepare WORKSPACE') {
@@ -67,12 +100,16 @@ pipeline {
                     script {
                         // print jenkins env configurations
                         sh 'env'
+
+                        // Load the necessary packages
+                        resultStatus = sharedLib.resource.ResultStatus
+
                         generalUtil = load("${env.WORKSPACE}/groovy/generalHelper.groovy")
                         jsUtil = load("${env.WORKSPACE}/groovy/jsHelper.groovy")
 
                         if (generalUtil.isBranchUpToDateWithRemote(PR_BRANCH)) {
-                            echo "Current branch is up-to-date with origin/${destinationBranch}. Aborting pipeline."
-                            currentBuild.result = 'ABORTED'
+                            echo 'Current branch is up-to-date with origin/${destinationBranch}. Aborting pipeline.'
+                            currentBuild.result = resultStatus.BUILD_STATUS.ABORTED
                             error('Branch is up to date, no changes.')
                         }
 
@@ -244,7 +281,7 @@ pipeline {
             steps {
                 dir("${PROJECT_DIR}") {
                     script {
-                        sh 'pwd'
+                        pwd()
                         String scannerHome = tool SONARQUBE_SCANNER
                         echo "SonarQube scanner located at: ${scannerHome}"
 
@@ -262,13 +299,15 @@ pipeline {
                 }
                 withCredentials([string(credentialsId: 'SonarQube', variable: 'SONAR_QUBE_AUTH_TOKEN')]) {
                     script {
-                        Map status = jsUtil.checkQualityGateStatus(SONAR_PROJECT_KEY , env.SONAR_QUBE_AUTH_TOKEN)
+                        Map status = generalUtil.checkQualityGateStatus(SONAR_PROJECT_KEY , env.SONAR_QUBE_AUTH_TOKEN)
 
-                        catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
-                            // groovylint-disable-next-line DuplicateStringLiteral
-                            if ((status.entireCodeStatus != 'OK') && (status.newCodeStatus != 'OK')) {
+                        catchError(buildResult: resultStatus.BUILD_STATUS.SUCCESS, stageResult: resultStatus.STAGE_STATUS.FAILURE) {
+                            final String STATUS_OK = 'OK'
+
+                            if ((status.entireCodeStatus != STATUS_OK) || (status.newCodeStatus != STATUS_OK)) {
+                                echo "Entire Code Status: ${status.entireCodeStatus}, New Code Status: ${status.newCodeStatus}"
                                 error('Quality gate failed!')
-                        } else {
+                            } else {
                                 echo 'Quality gate passed!'
                             }
                         }
diff --git a/JsJenkins/JenkinsfileDeployment b/JsJenkins/JenkinsfileDeployment
--- a/JsJenkins/JenkinsfileDeployment
+++ b/JsJenkins/JenkinsfileDeployment
@@ -1,6 +1,8 @@
 def generalUtil
 def jsUtil
 def mainBranches = ['main', 'master']
+def sharedLib // Use this variable to store the shared library, work as import statement
+def resultStatus // Use this variable to store the package of result status, work as import statement
 
 pipeline {
     agent any
@@ -51,26 +53,60 @@ pipeline {
     }
 
     stages {
+        stage('Load Shared Library') {
+            steps {
+                script {
+                    try {
+                        def LIBRARY_PATH = 'sharedLibraries'
+                        echo "Loading local shared library from ${WORKSPACE}/${LIBRARY_PATH}"
+
+                        // Create temporary Git repository
+                        sh """
+                            cd ${WORKSPACE}/${LIBRARY_PATH} && \
+                            (rm -rf .git || true) && \
+                            git init && \
+                            git add --all && \
+                            git commit -m 'init'
+                        """
+
+                        // Get the path of the temporary Git repository
+                        def repoPath = sh(returnStdout: true, script: 'pwd').trim() + "/${LIBRARY_PATH}"
+
+                        // Shared Library Registration
+                        sharedLib = library identifier: 'local-lib@master',
+                                retriever: modernSCM([$class: 'GitSCMSource', remote: "${repoPath}"]),
+                                changelog: false
+                        echo 'Successfully loaded shared library'
+                    } catch (Exception e) {
+                        echo "Failed to load shared library: ${e.message}"
+                        error('Shared Library Loading Failed')
+                    }
+                }
+            }
+        }
         // Deletes the cloned branch from the build machine after it has been merged into main.
         // This prevents the build machine's storage from capping out.
         stage('Delete Merged Branch') {
             steps {
                 script {
-                    // Aborts the pipeline if it's not merging into the main.
-                    if (!mainBranches.contains(DESTINATION_BRANCH)) {
-                        env.FAILURE_REASON = 'Not merging to the main branch. Exiting the pipeline...'
-                        currentBuild.result = 'ABORTED'
-                        error(env.FAILURE_REASON)
-                    }
+                    // Load the necessary packages
+                    resultStatus = sharedLib.resource.ResultStatus
 
                     generalUtil = load("${env.WORKSPACE}/groovy/generalHelper.groovy")
                     jsUtil = load("${env.WORKSPACE}/groovy/jsHelper.groovy")
 
-                    def branch_path = sh(script: "/usr/bin/find ../ -type d -name \"${PR_BRANCH}\"", returnStdout: true)
-                    branch_path = branch_path.trim()
-                    if (!branch_path.isEmpty()) {
-                        sh "rm -r -f \"${branch_path}\""
-                        sh "rm -r -f \"${branch_path}@tmp\""
+                    // Aborts the pipeline if it's not merging into the main.
+                    if (!mainBranches.contains(DESTINATION_BRANCH)) {
+                        env.FAILURE_REASON = 'Not merging to the main branch. Exiting the pipeline...'
+                        currentBuild.result = resultStatus.BUILD_STATUS.ABORTED
+                        error(env.FAILURE_REASON)
+                    }
+
+                    def branchPath = sh(script: "/usr/bin/find ../ -type d -name \"${PR_BRANCH}\"", returnStdout: true)
+                    branchPath = branchPath.trim()
+                    if (!branchPath.isEmpty()) {
+                        sh "rm -r -f \"${branchPath}\""
+                        sh "rm -r -f \"${branchPath}@tmp\""
                     }
 
                     // groovylint-disable-next-line DuplicateStringLiteral
@@ -188,11 +224,11 @@ pipeline {
                 }
                 withCredentials([string(credentialsId: 'SonarQube', variable: 'SONAR_QUBE_AUTH_TOKEN')]) {
                     script {
-                        Map status = jsUtil.checkQualityGateStatus(SONAR_PROJECT_KEY , env.SONAR_QUBE_AUTH_TOKEN)
+                        Map status = generalUtil.checkQualityGateStatus(SONAR_PROJECT_KEY , env.SONAR_QUBE_AUTH_TOKEN)
 
-                        catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
-                            // groovylint-disable-next-line DuplicateStringLiteral
-                            if ((status.entireCodeStatus != 'OK') && (status.newCodeStatus != 'OK')) {
+                        catchError(buildResult: resultStatus.BUILD_STATUS.SUCCESS, stageResult: resultStatus.STAGE_STATUS.FAILURE) {
+                            if ((status.entireCodeStatus != 'OK') || (status.newCodeStatus != 'OK')) {
+                                echo "Entire Code Status: ${status.entireCodeStatus}, New Code Status: ${status.newCodeStatus}"
                                 error('Quality gate failed!')
                             } else {
                                 echo 'Quality gate passed!'
@@ -267,11 +303,10 @@ pipeline {
                         echo "Server Project Version: ${project_server_version}"
 
                         // Check whether the server version in up-to-date
-                        /* groovylint-disable DuplicateStringLiteral */
-                        catchError(buildResult: 'UNSTABLE', stageResult: 'UNSTABLE') {
+                        catchError(buildResult: resultStatus.BUILD_STATUS.UNSTABLE, stageResult: resultStatus.STAGE_STATUS.UNSTABLE) {
                             if (!jsUtil.versionCompare(server_latest_version, project_server_version)) {
                                 warnError('Server version is not up to date. Skipping the deployment process.')
-                                currentBuild.result = 'UNSTABLE'
+                                currentBuild.result = resultStatus.BUILD_STATUS.UNSTABLE
                                 return // Skip server deployment process
                             }
                             echo 'Server version is up-to-date. Proceeding with deployment.'
@@ -343,11 +378,10 @@ pipeline {
                         echo "Client Project Version: ${project_client_version}"
 
                         // Check whether the client version in up-to-date
-                        // groovylint-disable-next-line
-                        catchError(buildResult: 'UNSTABLE', stageResult: 'UNSTABLE') {
+                        catchError(buildResult: resultStatus.BUILD_STATUS.UNSTABLE, stageResult: resultStatus.STAGE_STATUS.UNSTABLE) {
                             if (!jsUtil.versionCompare(client_latest_version, project_client_version)) {
                                 warnError('Client version is not up to date. Skipping the deployment process.')
-                                currentBuild.result = 'UNSTABLE'
+                                currentBuild.result = resultStatus.BUILD_STATUS.UNSTABLE
                                 return // Skip client deployment process
                             }
                             echo 'Client version is up-to-date. Proceeding with deployment.'
diff --git a/PipelineForJenkins/Jenkinsfile b/PipelineForJenkins/Jenkinsfile
--- a/PipelineForJenkins/Jenkinsfile
+++ b/PipelineForJenkins/Jenkinsfile
@@ -1,4 +1,6 @@
 def generalUtil
+def sharedLib // Use this variable to store the shared library, work as import statement
+def resultStatus // Use this variable to store the package of result status, work as import statement
 
 pipeline {
     agent any
@@ -54,33 +56,78 @@ pipeline {
         /* groovylint-enable DuplicateStringLiteral */
         PATH = "${JAVA_HOME}/bin:${GROOVY_HOME}/bin:${PATH}"
         JOB_REPO = "${PR_REPO_HTML}"
+
+        // Environmental variables for static analysis
+        SONARQUBE_SERVER = 'SonarServer'
+        SONARQUBE_SCANNER = 'sonarqube-scanner'
+        SONAR_PROJECT_KEY = "${env.JOB_NAME.split('/')[0]}-PR"
     }
 
     stages {
+        stage('Load Shared Library') {
+            steps {
+                script {
+                    try {
+                        def LIBRARY_PATH = 'sharedLibraries'
+                        echo "Loading local shared library from ${WORKSPACE}/${LIBRARY_PATH}"
+
+                        // Create temporary Git repository
+                        sh """
+                            cd ${WORKSPACE}/${LIBRARY_PATH} && \
+                            (rm -rf .git || true) && \
+                            git init && \
+                            git add --all && \
+                            git commit -m 'init'
+                        """
+
+                        // Get the path of the temporary Git repository
+                        def repoPath = sh(returnStdout: true, script: 'pwd').trim() + "/${LIBRARY_PATH}"
+
+                        // Shared Library Registration
+                        sharedLib = library identifier: 'local-lib@master',
+                                retriever: modernSCM([$class: 'GitSCMSource', remote: "${repoPath}"]),
+                                changelog: false
+                        echo 'Successfully loaded shared library'
+                    } catch (Exception e) {
+                        echo "Failed to load shared library: ${e.message}"
+                        error('Shared Library Loading Failed')
+                    }
+                }
+            }
+        }
         stage('Prepare Workspace') {
             steps {
                 script {
                     dir("${PROJECT_DIR}") {
-                        echo 'Preparing the workspace...'
-                        generalUtil = load("${env.WORKSPACE}/groovy/generalHelper.groovy")
+                        try {
+                            // Load the necessary packages
+                            resultStatus = sharedLib.resource.ResultStatus
 
-                        if (generalUtil.isBranchUpToDateWithRemote(PR_BRANCH) && !TEST_RUN.equals('Y')) {
-                            echo 'Local branch commit is up to date with remote branch, no changes. Aborting pipeline.'
-                            currentBuild.result = 'ABORTED'
-                            error('Branch is up to date, no changes.')
-                        }
+                            echo 'Preparing the workspace...'
+                            generalUtil = load("${env.WORKSPACE}/groovy/generalHelper.groovy")
 
-                        COMMIT_HASH = generalUtil.getFullCommitHash(env.WORKSPACE, PR_COMMIT)
+                            if (generalUtil.isBranchUpToDateWithRemote(PR_BRANCH) && !TEST_RUN.equals('Y')) {
+                                echo 'Local branch commit is up to date with remote branch, no changes. Aborting pipeline.'
+                                currentBuild.result = resultStatus.BUILD_STATUS.ABORTED
+                                error('Branch is up to date, no changes.')
+                            }
 
-                        // This sets environment variables for TICKET_NUMBER and FOLDER_NAME
-                        generalUtil.initializeEnvironment(env.WORKSPACE, COMMIT_HASH, PR_BRANCH)
+                            COMMIT_HASH = generalUtil.getFullCommitHash(env.WORKSPACE, PR_COMMIT)
 
-                        echo 'Cloning or updating repository...'
-                        generalUtil.cloneOrUpdateRepo(PROJECT_TYPE, env.WORKSPACE, PROJECT_DIR, REPO_SSH, params.PR_BRANCH)
+                            // This sets environment variables for TICKET_NUMBER and FOLDER_NAME
+                            generalUtil.initializeEnvironment(env.WORKSPACE, COMMIT_HASH, PR_BRANCH)
 
-                        echo "Checking out branch ${params.PR_BRANCH}..."
-                        dir(PROJECT_DIR) {
-                            generalUtil.checkoutBranch(PROJECT_DIR, params.PR_BRANCH)
+                            echo 'Cloning or updating repository...'
+                            generalUtil.cloneOrUpdateRepo(PROJECT_TYPE, env.WORKSPACE, PROJECT_DIR, REPO_SSH, params.PR_BRANCH)
+
+                            echo "Checking out branch ${params.PR_BRANCH}..."
+                            dir(PROJECT_DIR) {
+                                generalUtil.checkoutBranch(PROJECT_DIR, params.PR_BRANCH)
+                            }
+                        } catch (Exception e) {
+                            echo "Error in Prepare Workspace stage: ${e.getMessage()}"
+                            currentBuild.result = resultStatus.BUILD_STATUS.FAILURE
+                            error("Workspace preparation failed: ${e.getMessage()}")
                         }
                     }
                 }
@@ -103,6 +150,7 @@ pipeline {
                                 echo "Linting Groovy scripts in ${PROJECT_DIR}/groovy ..."
                                 npm-groovy-lint \\
                                     --failon error \\
+                                    --no-parse \\
                                     --output groovy-lint-report.json \\
                                     --config ${PROJECT_DIR}/.groovylintrc.groovy.json \\
                                     ${PROJECT_DIR}/groovy
@@ -123,7 +171,7 @@ pipeline {
                         """.stripIndent()
 
                         // Mark the stage as failed but let the pipeline continue if desired
-                        catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
+                        catchError(buildResult: resultStatus.BUILD_STATUS.SUCCESS, stageResult: resultStatus.STAGE_STATUS.FAILURE) {
                             error("Groovy linting failed (exit code ${exitCodeGroovy})")
                         }
                     }
@@ -138,6 +186,7 @@ pipeline {
                                 echo "Linting Jenkinsfiles in DLXJenkins, JsJenkins, PipelineForJenkins ..."
                                 npm-groovy-lint \\
                                     --failon error \\
+                                    --no-parse \\
                                     --output jenkins-lint-report.json \\
                                     --config ${PROJECT_DIR}/.groovylintrc.jenkins.json \\
                                     ${PROJECT_DIR}/DLXJenkins \\
@@ -158,8 +207,8 @@ pipeline {
                             ${COMMIT_HASH} \
                             Fail '${PROJECT_DIR}'
                         """.stripIndent()
-                        //groovylint-disable-next-line DuplicateMapLiteral, DuplicateStringLiteral
-                        catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
+
+                        catchError(buildResult: resultStatus.BUILD_STATUS.SUCCESS, stageResult: resultStatus.STAGE_STATUS.FAILURE) {
                             error("Jenkinsfile linting failed (exit code ${exitCodeJenkins})")
                         }
                     } else {
@@ -207,10 +256,13 @@ pipeline {
                 }
             }
         }
+
         stage('Run Unit Tests') {
             steps {
                 script {
-                    sh 'gradle test'
+                    sh """
+                    gradle test -PsharedLibraryDir=${env.WORKSPACE}/sharedLibraries
+                    """
                 }
             }
         }
@@ -221,13 +273,60 @@ pipeline {
                 }
             }
         }
+        // Runs static code analysis using SonarQube installed in Jenkins virtual machine.
+        stage('Static Analysis') {
+            steps {
+                dir("${PROJECT_DIR}") {
+                    pwd()
+                    script {
+                        catchError(buildResult: resultStatus.BUILD_STATUS.SUCCESS, stageResult: resultStatus.STAGE_STATUS.FAILURE) {
+                            String scannerHome = tool SONARQUBE_SCANNER
+                            echo "SonarQube scanner located at: ${scannerHome}"
+
+                            withSonarQubeEnv(SONARQUBE_SERVER) {
+                                String sonarCommand = "\"${scannerHome}/bin/sonar-scanner\" " +
+                            "\"-Dsonar.projectKey=${env.SONAR_PROJECT_KEY}\" " +
+                            '\"-Dsonar.host.url=http://localhost:9000/sonarqube\" ' +
+                            '\"-Dsonar.sources=.\" ' +
+                            '\"-Dsonar.log.level=DEBUG\" ' +
+                            '\"-Dsonar.verbose=true\" ' +
+                            '\"-Dsonar.lang.patterns.grvy="**/*.groovy,**/Jenkinsfile,**/JenkinsfileDeployment"\" ' +
+                            '\"-Dsonar.exclusions=**/python/log-template/logs.html,**/Builder.cs,**/build.gradle,**/Bash/**\" ' +
+                            '\"-Dsonar.python.version=3.10\"'
+
+                                echo "Executing SonarQube scanner with command: ${sonarCommand}"
+                                sh sonarCommand
+                            }
+                        }
+                    }
+                }
+
+                withCredentials([string(credentialsId: 'SonarQube', variable: 'SONAR_QUBE_AUTH_TOKEN')]) {
+                    script {
+                        catchError(buildResult: resultStatus.BUILD_STATUS.SUCCESS, stageResult: resultStatus.STAGE_STATUS.FAILURE) {
+                            Map status = generalUtil.checkQualityGateStatus(SONAR_PROJECT_KEY, env.SONAR_QUBE_AUTH_TOKEN)
+
+                            final String STATUS_OK = 'OK'
+
+                            if ((status.entireCodeStatus != STATUS_OK) || (status.newCodeStatus != STATUS_OK)) {
+                                echo "Entire Code Status: ${status.entireCodeStatus}, New Code Status: ${status.newCodeStatus}"
+                                error('Quality gate failed!')
+                            } else {
+                                echo 'Quality gate passed!'
+                            }
+                        }
+                    }
+                }
+            }
+        }
     }
 
     post {
         always {
             script {
                 echo 'Cleaning up the workspace...'
-            // deleteDir() this is commented out for now, but in future we can do clean up if needed
+                currentBuild.description = "${PR_BRANCH}"
+                // deleteDir() this is commented out for now, but in future we can do clean up if needed
             }
         }
         success {
